import {test} from 'node:test';import assert from 'node:assert/strict';import {Collection,ChannelType as T} from 'discord.js';import {deletionHandler} from '../src/delete-structure.js';
function fixture(){let time=0,admin=true;const channels=new Collection(),deleted=[],logs=[],locks=new Set();const guild={id:'11111111111111111',name:'Teste',ownerId:'owner',members:{fetch:async()=>({permissions:{has:()=>admin}})},channels:{fetch:async()=>channels}};
 const add=(id,type=T.GuildText)=>{const ch={id,type,deletable:true,delete:async()=>{deleted.push(id);channels.delete(id)}};channels.set(id,ch);return ch;};add('text');add('call',T.GuildVoice);add('category',T.GuildCategory);add('origin');
 const handler=deletionHandler({guilds:{fetch:async()=>guild}},[{guild:guild.id}],locks,{now:()=>time,log:s=>logs.push(s)});
 const interaction=(custom,user='admin',guildId=guild.id)=>({guildId,channelId:'origin',user:{id:user},commandName:'deletar',customId:custom,isChatInputCommand:()=>!custom,isButton:()=>!!custom,deferReply:async()=>{},editReply:async function(r){this.result=r;}});
 const ask=async()=>{const i=interaction();await handler(i);return {i,key:i.result.components?.[0].components[0].data.custom_id}};
 return {channels,deleted,logs,locks,handler,interaction,ask,add,setTime:v=>time=v,setAdmin:v=>admin=v};}
test('delete previews all resources without changing them and deletes only after confirmation',async()=>{const f=fixture(),{i,key}=await f.ask();assert.match(i.result.content,/3 canais e 1 categorias/);assert.equal(f.deleted.length,0);f.add('new-channel');await f.handler(f.interaction(key));assert.equal(f.deleted.length,4);assert.equal(f.deleted.at(-1),'origin');assert.ok(f.channels.has('new-channel'));assert.equal(f.locks.size,0);assert.ok(f.logs.some(x=>x.includes('apagados=4')));await f.handler(f.interaction(key));assert.equal(f.deleted.length,4);});
test('delete refuses outsiders, other guilds and another admin using the confirmation',async()=>{const f=fixture();f.setAdmin(false);const no=f.interaction();await f.handler(no);assert.match(no.result.content,/Somente/);f.setAdmin(true);const {key}=await f.ask();await f.handler(f.interaction(key,'other-admin'));await f.handler(f.interaction(key,'admin','other-guild'));assert.equal(f.deleted.length,0);await f.handler(f.interaction(key));assert.equal(f.deleted.length,4);});
test('confirmation expires or can be cancelled without deleting',async()=>{const f=fixture();let {key}=await f.ask();f.setTime(60001);await f.handler(f.interaction(key));assert.equal(f.deleted.length,0);({key}=await f.ask());await f.handler(f.interaction(key.replace(':confirm:',':cancel:')));await f.handler(f.interaction(key));assert.equal(f.deleted.length,0);});
test('admin permission and channel deletability are checked again before any deletion',async()=>{const f=fixture();let {key}=await f.ask();f.setAdmin(false);await f.handler(f.interaction(key));assert.equal(f.deleted.length,0);f.setAdmin(true);({key}=await f.ask());f.channels.get('call').deletable=false;await f.handler(f.interaction(key));assert.equal(f.deleted.length,0);assert.equal(f.locks.size,0);});
test('delete cannot overlap create or delete for the same guild',async()=>{const f=fixture();const {key}=await f.ask();f.locks.add('11111111111111111');await f.handler(f.interaction(key));assert.equal(f.deleted.length,0);assert.equal(f.locks.size,1);});
test('partial deletion reports failure and keeps the failed resource for a new review',async()=>{const f=fixture();f.channels.get('call').delete=async()=>{throw Object.assign(new Error('permission'),{code:50013})};const {key}=await f.ask();await f.handler(f.interaction(key));assert.equal(f.deleted.length,3);assert.ok(f.channels.has('call'));assert.ok(f.logs.some(x=>x.includes('falhas=1')));assert.equal(f.locks.size,0);});
test('lost reply after originating channel removal does not retry deletion',async()=>{const f=fixture();const {key}=await f.ask();const i=f.interaction(key);i.editReply=async()=>{if(!f.channels.has('origin'))throw Error('Unknown channel')};await f.handler(i);assert.equal(f.deleted.length,4);assert.equal(f.locks.size,0);});
