import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {parseEnv} from 'node:util';
import {boot,reporter,StartupError,systemChecks,checkDatabase} from '../src/preflight.js';
import {validateEnvironment,ID_FIELDS,ROLE_ENV} from '../src/config-rules.js';
import {serializeEnv,parseEnvFile} from '../src/env-codec.js';
import {validateDiscord} from '../src/discord-checks.js';
import {ChannelType,PermissionFlagsBits as P} from 'discord.js';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {passwordHash} from '../src/security.js';
const base=()=>({NODE_ENV:'production',BOT_ENABLED:'false',APP_ORIGIN:'https://ifj.example.org',DATABASE_URL:'postgresql://postgres:TEST_PRIVATE_PASSWORD@db.example.org:5432/postgres?sslmode=verify-full',SESSION_SECRET:'TEST_PRIVATE_SECRET_'.repeat(3),INITIAL_ADMIN_USERNAME:'admin',INITIAL_ADMIN_PASSWORD:'TEST_ADMIN_PASSWORD_123'});
function fixture(failAt){
 const events=[],logs=[];const step=name=>async()=>{events.push(name);if(name===failAt)throw Object.assign(new Error('Do not log TEST_PRIVATE_PASSWORD'),{code:name==='connect'?'28P01':undefined});};
 const pool={query:step('connect'),end:step('pool-end')};const bot={start:step('discord-login'),validate:step('discord-checks'),activate:()=>events.push('activate'),stop:step('bot-stop')};
 const options={env:base(),makePool:()=>pool,initialize:step('schema'),makeBot:()=>bot,makeApp:()=>{events.push('app');return {};},listen:async()=>{await step('listen')();return {close:cb=>{events.push('close');cb();}};},log:reporter(s=>logs.push(s)),checks:{system:step('system'),database:step('database')}};
 return {events,logs,options};
}
function botEnv(){const env=base();env.BOT_ENABLED='true';env.DISCORD_TOKEN='valid-format-but-not-real-token-for-tests';let x=10000000000000000n;for(const n of [1,2])for(const suffix of ID_FIELDS)env[`DIV_${n}_${suffix}`]=String(++x);return env;}
test('environment reports multiple errors without including values',()=>{const env={...base(),APP_ORIGIN:'https://configurar.invalid',BOT_ENABLED:'typo',SESSION_SECRET:'PRIVATE'};const errors=validateEnvironment(env).filter(x=>!x.ok);assert.ok(errors.some(e=>e.key==='APP_ORIGIN'));assert.ok(errors.some(e=>e.key==='BOT_ENABLED'));assert.ok(!JSON.stringify(errors).includes('PRIVATE'));});
test('invalid configuration blocks pool, bot and HTTP listener',async()=>{const f=fixture();f.options.env.APP_ORIGIN='bad';await assert.rejects(boot(f.options));assert.deepEqual(f.events,[]);assert.ok(f.logs.some(x=>x.includes('BLOQUEADO')));});
for(const failure of ['system','connect','schema','database'])test(`failure at ${failure} never opens HTTP`,async()=>{const f=fixture(failure);await assert.rejects(boot(f.options));assert.ok(!f.events.includes('listen'));assert.ok(!f.events.includes('activate'));assert.ok(!f.logs.join('\n').includes('TEST_PRIVATE_PASSWORD'));});
for(const failure of ['discord-login','discord-checks'])test(`${failure} failure prevents server and cleans resources`,async()=>{const f=fixture(failure);f.options.env=botEnv();await assert.rejects(boot(f.options));assert.ok(!f.events.includes('listen'));assert.ok(f.events.includes('bot-stop'));assert.ok(f.events.includes('pool-end'));});
test('success starts listener only after checks and activates work last',async()=>{const f=fixture();f.options.env=botEnv();await boot(f.options);assert.ok(f.events.indexOf('listen')>f.events.indexOf('discord-checks'));assert.equal(f.events.at(-1),'activate');assert.ok(f.logs.at(-1).includes('PRONTO'));});
test('BOT_ENABLED=false explicitly skips Discord and starts only panel',async()=>{const f=fixture();await boot(f.options);assert.ok(!f.events.includes('discord-login'));assert.ok(!f.events.includes('activate'));assert.ok(f.logs.some(x=>x.includes('DISPENSADO')&&x.includes('Discord')));});
test('real server process exits 1 for invalid vars and never reports started',()=>{const r=spawnSync(process.execPath,['src/server.js'],{cwd:new URL('../',import.meta.url),env:{PATH:process.env.PATH,NODE_ENV:'production',SESSION_SECRET:'MY_PRIVATE_LEAK_TEST'},encoding:'utf8',timeout:10000});assert.equal(r.status,1);assert.match(r.stdout,/BLOQUEADO/);assert.doesNotMatch(r.stdout+r.stderr,/MY_PRIVATE_LEAK_TEST/);assert.doesNotMatch(r.stdout,/\[PRONTO\]/);});
test('system self-test validates actual files, password hash and permissions',async()=>{await systemChecks();});
test('database test performs rollback and leaves no test records',async()=>{
 const db=new PGlite();try{await db.exec(await readFile(new URL('../src/schema.sql',import.meta.url),'utf8'));await db.query("INSERT INTO staff(username,password_hash,role) VALUES('admin',$1,'admin')",[await passwordHash('test-safe-password')]);const pool={query:async(s,a)=>{const r=await db.query(s,a);return {...r,rowCount:r.affectedRows||r.rows.length};},connect:async()=>({...pool,release(){}})};await checkDatabase(pool);assert.equal((await db.query('SELECT * FROM audit')).rows.length,0);await db.query('UPDATE staff SET active=false');await assert.rejects(checkDatabase(pool),/administrador ativo/);}finally{await db.close();}
});
test('env serialization matches Node parser with # spaces quotes and literal slashes',()=>{const values={SESSION_SECRET:'ab#cd=42 with space',DATABASE_URL:'postgresql://a:b%23c@host/db?sslmode=verify-full',SINGLE:"It's valid",LITERAL:'literal\\nvalue',DOUBLE:'a"b',BOTH:'both\'and"quote',EMPTY:''};const text=serializeEnv(values);assert.deepEqual(parseEnv(text),values);assert.deepEqual(parseEnvFile(text),values);assert.throws(()=>serializeEnv({BAD:'line\ninjection'}));assert.throws(()=>parseEnvFile('KEY=one\nKEY=two'));});
function discordFixture(){const id='10000000000000001',member={id:'10000000000000002',managed:false,permissions:{has:()=>false}},admin={id:'10000000000000003',permissions:{has:()=>false}};const me={permissions:{has:()=>true},roles:{highest:{comparePositionTo:()=>1}}};const d={id:1,guild:id,memberRole:member.id,adminRole:admin.id,category:'10000000000000004',verification:'10000000000000005',wanted:'10000000000000006',tickets:'10000000000000007',reports:'10000000000000008',welcome:'10000000000000009',guide:'10000000000000010'};d.rankRoles=Object.fromEntries(Object.keys(ROLE_ENV).map((key,i)=>[key,String(30000000000000000n+BigInt(i))]));const roles=new Map([[member.id,member],[admin.id,admin],...Object.values(d.rankRoles).map(id=>[id,{id,permissions:{has:()=>false}}])]);const everyone={id};const channels=new Map();for(const key of ['category','verification','wanted','tickets','reports','welcome','guide'])channels.set(d[key],{guildId:id,type:key==='category'?ChannelType.GuildCategory:ChannelType.GuildText,permissionsFor:()=>({has:()=>true})});const g={id,roles:{fetch:async()=>roles,everyone},members:{fetchMe:async()=>me},channels:{fetch:async ch=>channels.get(ch)}};return {d,member,channels,me,client:{isReady:()=>true,guilds:{fetch:async()=>g}},log:reporter(()=>{})};}
test('Discord read-only checks accept correct mocks and reject wrong role hierarchy/channel',async()=>{const f=discordFixture();await validateDiscord(f.client,{divisions:[f.d]},f.log);f.me.roles.highest.comparePositionTo=()=>-1;await assert.rejects(validateDiscord(f.client,{divisions:[f.d]},f.log),/abaixo/);f.me.roles.highest.comparePositionTo=()=>1;f.channels.get(f.d.verification).type=ChannelType.GuildVoice;await assert.rejects(validateDiscord(f.client,{divisions:[f.d]},f.log),/canal de texto/);});
