import {test} from 'node:test';import assert from 'node:assert/strict';import {PermissionFlagsBits as P} from 'discord.js';
import {ROLE_ENV} from '../src/config-rules.js';import {wantedRoles,synchronizeRoles,assertManagedRoles} from '../src/role-policy.js';
function fixture(division=1){const d={id:division,memberRole:'member',adminRole:'team',rankRoles:Object.fromEntries(Object.keys(ROLE_ENV).map(k=>[k,k]))},roles=new Map(['member','team',...Object.keys(ROLE_ENV)].map(id=>[id,{id,permissions:{has:()=>false}}])),me={roles:{highest:{comparePositionTo:()=>1}}};const events=[],cache=new Set(['unrelated']);const user={roles:{cache,add:async id=>{events.push(['add',id]);cache.add(id);},remove:async id=>{events.push(['remove',id]);cache.delete(id);}}};const g={id:'guild',roles:{fetch:async()=>roles},members:{fetchMe:async()=>me}};return {d,g,roles,me,events,user,cache};}
test('unverified users receive nothing; each configured rank gets its own role after verification',async()=>{
 const f=fixture();for(const [name,key]of [['Líder','leader'],['Sub-líder','subleader'],['High member','high'],['Moderador','moderator'],['Recrutador','recruiter'],['Veterano','veteran'],['Novato','rookie'],['Aliado','ally']]){
 const m={account_kind:'membro',division:1,member_rank:name,verified:false};assert.equal(wantedRoles(m,f.d).size,0);m.verified=true;const wanted=wantedRoles(m,f.d);assert.ok(wanted.has(key));assert.ok(wanted.has('member'));assert.equal(wanted.has('team'),['leader','subleader','moderator'].includes(key));
 }
 assert.deepEqual([...wantedRoles({verified:true,division:1,account_kind:'membro',member_rank:'Patente personalizada'},f.d)],['member']);
});
test('division and alliance rules apply to access, rank and team roles together',()=>{const {d}=fixture(2);for(const rank of ['Líder','Sub líder','High member'])assert.ok(wantedRoles({account_kind:'membro',division:1,member_rank:rank,verified:true},d).has('member'));assert.equal(wantedRoles({account_kind:'membro',division:1,member_rank:'Moderador',verified:true},d).size,0);const ally=wantedRoles({account_kind:'aliado',member_rank:'Líder',division:1,verified:true},d);assert.ok(ally.has('ally'));assert.equal(ally.has('team'),false);});
test('promotion grants team; demotion and revocation remove stale roles and preserve unrelated roles',async()=>{const f=fixture();const m={account_kind:'membro',division:1,verified:true,member_rank:'Sub líder'};await synchronizeRoles(f.g,f.d,f.user,m);assert.deepEqual([...f.cache].sort(),['member','subleader','team','unrelated'].sort());m.member_rank='Moderador';await synchronizeRoles(f.g,f.d,f.user,m);assert.ok(!f.cache.has('subleader'));assert.ok(f.cache.has('moderator'));m.member_rank='Recrutador';await synchronizeRoles(f.g,f.d,f.user,m);assert.ok(!f.cache.has('team'));assert.ok(!f.cache.has('moderator'));assert.ok(f.cache.has('recruiter'));m.verified=false;await synchronizeRoles(f.g,f.d,f.user,m);assert.deepEqual([...f.cache],['unrelated']);});
test('deleted IFJ revokes all managed roles; runtime checks reject elevated or unmanageable roles',async()=>{const f=fixture();for(const id of f.roles.keys())f.cache.add(id);await synchronizeRoles(f.g,f.d,f.user,null);assert.deepEqual([...f.cache],['unrelated']);f.roles.get('team').permissions.has=bit=>bit===P.Administrator;assert.throws(()=>assertManagedRoles(f.g,f.d,f.roles,f.me));await assert.rejects(synchronizeRoles(f.g,f.d,f.user,{verified:true,division:1,member_rank:'Líder',account_kind:'membro'}));assert.deepEqual([...f.cache],['unrelated']);});
